version: "3"
services:
  zookeeper:
    container_name: zookeeper
    networks: ["vnet"]
    hostname: zookeeper.vnet
    image: wurstmeister/zookeeper:latest
    expose: ["2181", "9998"]
  hadoop:
    container_name: hadoop
    networks: ["vnet"]
    hostname: hadoop.vnet
    image: cygni/7-databases:hadoop
    depends_on:
      - zookeeper
    expose: ["8020", "8088", "9000", "19888", "50070"]
    ports:
      # HDFS
      - 50070:50070
      # Yarn
      - 8088:8088
  hbase:
    container_name: hbase
    networks: ["vnet"]
    hostname: hbase.vnet
    image: cygni/7-databases:hbase
    depends_on:
      - hadoop
      - zookeeper
    expose: ["9090", "9095"]
    ports:
      - 9095:9095
      - 16010:16010
  hue:
    container_name: hue
    networks: ["vnet"]
    hostname: hue.vnet
    image: cygni/7-databases:hue
    depends_on:
      - hadoop
      - hbase
    dns: 8.8.8.8
    ports:
      - 8888:8888
    entrypoint: ["./build/env/bin/hue", "runserver_plus", "0.0.0.0:8888"]
networks:
  vnet:
    external:
      name: vnet